name: xagent
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - jupyterlab
  - pip=23.0.1
  - pip:
    - scikit-learn==0.23.0
    - simcse==0.4
    - alibi==0.6.1
    - shap==0.40.0
    - openml==0.12.2
    - scipy==1.5.4
    - dtreeviz==1.3
    - graphviz==0.16
    - dice-ml==0.7.2
    - anchor-exp==0.0.2.0
    - keras==2.6.0
    - tensorflow==2.5.0
    - spacy==3.1.4
    - numpy==1.19.5
    - streamlit==1.28.2
    - protobuf==3.20.3
    - accelerate==0.23.0
    - transformers==4.34.0
    - keras==2.5.0rc0
    - pytest==7.4.2